<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' => 'acid buret', 'quantity' => 11, 'brand' => 'Pyrex'],
            ['name' => 'acid buret', 'quantity' => 1, 'brand' => 'Mc'],
            ['name' => 'acid buret', 'quantity' => 2, 'brand' => 'brandless'],
            ['name' => 'acid dropper (glass long)', 'quantity' => 10, 'brand' => ''],
            ['name' => 'acid dropper (glass short)', 'quantity' => 17, 'brand' => ''],
            ['name' => 'acid dropper (plastic)', 'quantity' => 15, 'brand' => ''],
            ['name' => 'alcohol lamp', 'quantity' => 25, 'brand' => ''],
            ['name' => 'base buret', 'quantity' => 7, 'brand' => 'brandless'],
            ['name' => 'base buret', 'quantity' => 6, 'brand' => 'germany'],
            ['name' => 'base buret tube', 'quantity' => 1, 'brand' => ''],
            ['name' => 'beaker 100 ml', 'quantity' => 4, 'brand' => 'pyrex'],
            ['name' => 'beaker 1000ml', 'quantity' => 9, 'brand' => 'pyrex'],
            ['name' => 'beaker 150 ml', 'quantity' => 75, 'brand' => 'pyrex'],
            ['name' => 'beaker 250 ml', 'quantity' => 49, 'brand' => 'pyrex'],
            ['name' => 'beaker 400 ml', 'quantity' => 42, 'brand' => 'pyrex'],
            ['name' => 'beaker 400 ml', 'quantity' => 1, 'brand' => 'boeco'],
            ['name' => 'beaker 400 ml', 'quantity' => 1, 'brand' => 'duran'],
            ['name' => 'beaker 50 ml', 'quantity' => 63, 'brand' => 'pyrex'],
            ['name' => 'beaker 600 ml', 'quantity' => 14, 'brand' => 'pyrex'],
            ['name' => 'bell jar big', 'quantity' => 2, 'brand' => ''],
            ['name' => 'bell jar small', 'quantity' => 3, 'brand' => ''],
            ['name' => 'big spoon', 'quantity' => 7, 'brand' => ''],
            ['name' => 'buret clamp iron', 'quantity' => 13, 'brand' => ''],
            ['name' => 'buret clamp plastic', 'quantity' => 8, 'brand' => ''],
            ['name' => 'centrifuge tube 50 ml', 'quantity' => 52, 'brand' => 'plastic'],
            ['name' => 'centrifuge tube 50 ml', 'quantity' => 65, 'brand' => ''],
            ['name' => 'clay triangle', 'quantity' => 14, 'brand' => ''],
            ['name' => 'cork rubber stopper', 'quantity' => 93, 'brand' => ''],
            ['name' => 'cork wood', 'quantity' => 71, 'brand' => ''],
            ['name' => 'crucible tong (long)', 'quantity' => 1, 'brand' => ''],
            ['name' => 'crucible tong (small)', 'quantity' => 9, 'brand' => ''],
            ['name' => 'crucibles with cover', 'quantity' => 12, 'brand' => ''],
            ['name' => 'dissecting set', 'quantity' => 21, 'brand' => ''],
            ['name' => 'distilling flask 500 ml', 'quantity' => 2, 'brand' => 'pyrex'],
            ['name' => 'droppers', 'quantity' => 201, 'brand' => ''],
            ['name' => 'durham', 'quantity' => 374, 'brand' => ''],
            ['name' => 'electric microscope', 'quantity' => 12, 'brand' => ''],
            ['name' => 'erlenmeyer flask 1000 ml', 'quantity' => 2, 'brand' => 'pyrex'],
            ['name' => 'erlenmeyer flask 125 ml', 'quantity' => 5, 'brand' => 'kimax'],
            ['name' => 'erlenmeyer flask 125 ml', 'quantity' => 2, 'brand' => 'pyrex'],
            ['name' => 'erlenmeyer flask 250 ml', 'quantity' => 3, 'brand' => 'duran'],
            ['name' => 'erlenmeyer flask 250 ml', 'quantity' => 1, 'brand' => 'GCF'],
            ['name' => 'erlenmeyer flask 250 ml', 'quantity' => 109, 'brand' => 'pyrex'],
            ['name' => 'erlenmeyer flask 50 ml', 'quantity' => 4, 'brand' => 'pyrex'],
            ['name' => 'erlenmeyer flask 50 ml', 'quantity' => 4, 'brand' => 'jenna glass'],
            ['name' => 'erlenmeyer flask 500 ml', 'quantity' => 19, 'brand' => 'pyrex'],
            ['name' => 'evaporating dish', 'quantity' => 22, 'brand' => ''],
            ['name' => 'florence flask', 'quantity' => 2, 'brand' => 'kimax'],
            ['name' => 'forceps', 'quantity' => 48, 'brand' => ''],
            ['name' => 'funnel long stem', 'quantity' => 1, 'brand' => 'brandless'],
            ['name' => 'funnel long stem', 'quantity' => 4, 'brand' => 'pyrex'],
            ['name' => 'funnel long stem', 'quantity' => 1, 'brand' => 'sterglass'],
            ['name' => 'funnel long stem', 'quantity' => 3, 'brand' => 'tenshiang'],
            ['name' => 'funnel short stem', 'quantity' => 67, 'brand' => 'pyrex'],
            ['name' => 'gaduated cylinder 10 ml', 'quantity' => 5, 'brand' => 'brandless'],
            ['name' => 'gaduated cylinder 50 ml', 'quantity' => 11, 'brand' => 'pyrex'],
            ['name' => 'graduated cylinder 10 ml', 'quantity' => 36, 'brand' => 'pyrex'],
            ['name' => 'graduated cylinder 100 ml plastic', 'quantity' => 1, 'brand' => 'brandless'],
            ['name' => 'graduated cylinder 1000 ml', 'quantity' => 2, 'brand' => 'plastic'],
            ['name' => 'graduated cylinder 100ml glass', 'quantity' => 10, 'brand' => 'pyrex'],
            ['name' => 'graduated cylinder 25 ml', 'quantity' => 17, 'brand' => 'pyrex'],
            ['name' => 'graduated cylinder 250 ml', 'quantity' => 1, 'brand' => 'MC'],
            ['name' => 'graduated cylinder 250 ml', 'quantity' => 1, 'brand' => 'LMS'],
            ['name' => 'graduated cylinder 250 ml', 'quantity' => 1, 'brand' => 'IDI'],
            ['name' => 'graduated cylinder 250 ml', 'quantity' => 13, 'brand' => 'pyrex'],
            ['name' => 'graduated cylinder 500 ml', 'quantity' => 1, 'brand' => 'pyrex'],
            ['name' => 'graduated cylinder 500 ml', 'quantity' => 1, 'brand' => 'plastic'],
            ['name' => 'hand lens', 'quantity' => 8, 'brand' => ''],
            ['name' => 'hockey stick', 'quantity' => 18, 'brand' => ''],
            ['name' => 'hot plate', 'quantity' => 1, 'brand' => 'IKA'],
            ['name' => 'hot plate', 'quantity' => 1, 'brand' => 'Torrey pines'],
            ['name' => 'inoculating loop', 'quantity' => 59, 'brand' => ''],
            ['name' => 'inoculating needle', 'quantity' => 32, 'brand' => ''],
            ['name' => 'iron clamp', 'quantity' => 33, 'brand' => ''],
            ['name' => 'iron ring', 'quantity' => 18, 'brand' => ''],
            ['name' => 'iron stand', 'quantity' => 17, 'brand' => ''],
            ['name' => 'light compound miroscope', 'quantity' => 12, 'brand' => ''],
            ['name' => 'meter stick wood', 'quantity' => 5, 'brand' => ''],
            ['name' => 'micro pipette 1 ml', 'quantity' => 1, 'brand' => 'Mc'],
            ['name' => 'micro pipette 1 ml', 'quantity' => 10, 'brand' => 'pyrex #7065'],
            ['name' => 'micro pipette 1 ml', 'quantity' => 24, 'brand' => 'pyrex #7085'],
            ['name' => 'micro pipette 1 ml', 'quantity' => 3, 'brand' => 'pyrex #7102'],
            ['name' => 'micro pipette 10 ml', 'quantity' => 1, 'brand' => 'broken'],
            ['name' => 'micro pipette 10 ml', 'quantity' => 2, 'brand' => 'EM'],
            ['name' => 'micro pipette 10 ml', 'quantity' => 3, 'brand' => 'pyrex #7065'],
            ['name' => 'micro pipette 10 ml', 'quantity' => 18, 'brand' => 'pyrex #7085'],
            ['name' => 'micro pipette 10 ml', 'quantity' => 2, 'brand' => 'pyrex #7102'],
            ['name' => 'micro pipette 10 ml', 'quantity' => 1, 'brand' => 'Swift'],
            ['name' => 'micro pipette 2 ml', 'quantity' => 1, 'brand' => 'Crack top'],
            ['name' => 'micro pipette 2 ml', 'quantity' => 1, 'brand' => 'EXB'],
            ['name' => 'micro pipette 2 ml', 'quantity' => 6, 'brand' => 'pyrex #7085'],
            ['name' => 'micro pipette 2 ml', 'quantity' => 10, 'brand' => 'pyrex #7102'],
            ['name' => 'micro pipette 25 ml', 'quantity' => 9, 'brand' => 'MBL'],
            ['name' => 'micro pipette 25 ml', 'quantity' => 5, 'brand' => 'plastic'],
            ['name' => 'micro pipette 5 ml', 'quantity' => 2, 'brand' => 'Emil'],
            ['name' => 'micro pipette 5 ml', 'quantity' => 2, 'brand' => 'Kimax'],
            ['name' => 'micro pipette 5 ml', 'quantity' => 6, 'brand' => 'pyrex #7065'],
            ['name' => 'micro pipette 5 ml', 'quantity' => 1, 'brand' => 'pyrex #7083'],
            ['name' => 'micro pipette 5 ml', 'quantity' => 13, 'brand' => 'pyrex #7085'],
            ['name' => 'mortar and pestle', 'quantity' => 6, 'brand' => ''],
            ['name' => 'petri dish', 'quantity' => 2, 'brand' => 'kimax bottom;brandless cover'],
            ['name' => 'petri dish', 'quantity' => 6, 'brand' => 'pyrex bottom;brandless cover'],
            ['name' => 'petri dish ', 'quantity' => 37, 'brand' => 'glass brandless'],
            ['name' => 'petri dish ', 'quantity' => 3, 'brand' => 'kimax set'],
            ['name' => 'petri dish ', 'quantity' => 2, 'brand' => 'plastic'],
            ['name' => 'petri dish ', 'quantity' => 149, 'brand' => 'pyrex set'],
            ['name' => 'rotavap flask 250 ml', 'quantity' => 3, 'brand' => 'buchi'],
            ['name' => 'rubber aspirator (big)', 'quantity' => 35, 'brand' => ''],
            ['name' => 'rubber aspirator (small)', 'quantity' => 72, 'brand' => ''],
            ['name' => 'rubber aspirator 3-way', 'quantity' => 6, 'brand' => ''],
            ['name' => 'seed float', 'quantity' => 17, 'brand' => ''],
            ['name' => 'separatory funnel 250 ml', 'quantity' => 2, 'brand' => 'pyrex'],
            ['name' => 'separatory funnel 250 ml', 'quantity' => 2, 'brand' => 'bomex'],
            ['name' => 'separatory funnel 250 ml', 'quantity' => 5, 'brand' => 'brandless'],
            ['name' => 'separatory funnel 500 ml', 'quantity' => 1, 'brand' => 'duran'],
            ['name' => 'slate', 'quantity' => 8, 'brand' => ''],
            ['name' => 'small spoon', 'quantity' => 9, 'brand' => ''],
            ['name' => 'spatula', 'quantity' => 18, 'brand' => ''],
            ['name' => 'spot plate', 'quantity' => 12, 'brand' => ''],
            ['name' => 'stirring rod', 'quantity' => 50, 'brand' => ''],
            ['name' => 'stove', 'quantity' => 2, 'brand' => ''],
            ['name' => 'test tube 6"', 'quantity' => 553, 'brand' => 'pyrex'],
            ['name' => 'test tube brush', 'quantity' => 83, 'brand' => ''],
            ['name' => 'testube rack blue 40 holes', 'quantity' => 12, 'brand' => ''],
            ['name' => 'testube rack metal white', 'quantity' => 2, 'brand' => ''],
            ['name' => 'testube rack red 40 holes', 'quantity' => 9, 'brand' => ''],
            ['name' => 'testube rack white 40 holes', 'quantity' => 1, 'brand' => ''],
            ['name' => 'testube rack wire', 'quantity' => 19, 'brand' => ''],
            ['name' => 'testube rack wood', 'quantity' => 10, 'brand' => ''],
            ['name' => 'testube w/ screwcap(6")', 'quantity' => 126, 'brand' => 'pyrex'],
            ['name' => 'themometer', 'quantity' => 17, 'brand' => ''],
            ['name' => 'tripod', 'quantity' => 23, 'brand' => ''],
            ['name' => 'tripod', 'quantity' => 23, 'brand' => ''],
            ['name' => 'tripod ring', 'quantity' => 4, 'brand' => ''],
            ['name' => 'volumetric flask 100 ml', 'quantity' => 28, 'brand' => 'pyrex'],
            ['name' => 'volumetric flask 100 ml', 'quantity' => 1, 'brand' => 'Normchliff'],
            ['name' => 'volumetric flask 1000 ml', 'quantity' => 8, 'brand' => 'pyrex'],
            ['name' => 'volumetric flask 10ml', 'quantity' => 9, 'brand' => ''],
            ['name' => 'volumetric flask 25 ml', 'quantity' => 10, 'brand' => 'pyrex'],
            ['name' => 'volumetric flask 250 ml', 'quantity' => 1, 'brand' => 'duran'],
            ['name' => 'volumetric flask 250 ml', 'quantity' => 1, 'brand' => 'YS'],
            ['name' => 'volumetric flask 250 ml', 'quantity' => 1, 'brand' => 'MC'],
            ['name' => 'volumetric flask 250 ml', 'quantity' => 13, 'brand' => 'pyrex'],
            ['name' => 'volumetric flask 50 ml', 'quantity' => 1, 'brand' => 'brandless'],
            ['name' => 'volumetric flask 50 ml', 'quantity' => 1, 'brand' => 'EMIL'],
            ['name' => 'volumetric flask 50 ml', 'quantity' => 26, 'brand' => 'pyrex'],
            ['name' => 'volumetric flask 500 ml', 'quantity' => 13, 'brand' => 'pyrex'],
            ['name' => 'wash bottle', 'quantity' => 26, 'brand' => ''],
            ['name' => 'watchglass', 'quantity' => 25, 'brand' => 'pyrex'],
            ['name' => 'wire gauze', 'quantity' => 23, 'brand' => ''],
            ['name' => 'analytical balance', 'description' => ' Ohaus', 'quantity' => 1, 'acquisitioncost' => 67500, 'wattage' => 4, 'firsthour' => 42, 'succeeding' => 5],
            ['name' => 'analytical balance', 'description' => ' Sartorius', 'quantity' => 1, 'acquisitioncost' => 77500, 'wattage' => 16, 'firsthour' => 48, 'succeeding' => 5],
            ['name' => 'autoclave', 'description' => ' Sturdy SA-252F', 'quantity' => 1, 'acquisitioncost' => 120000, 'wattage' => 2063, 'firsthour' => 88, 'succeeding' => 17],
            ['name' => 'autoclave', 'description' => ' Sturdy SA-300VL', 'quantity' => 1, 'acquisitioncost' => 230000, 'wattage' => 1900, 'firsthour' => 146, 'succeeding' => 15],
            ['name' => 'bacticinerator', 'description' => ' McCormick', 'quantity' => 1, 'acquisitioncost' => 46055, 'wattage' => 135, 'firsthour' => 31, 'succeeding' => 5],
            ['name' => 'Biosafety cabinet', 'description' => ' Esco', 'quantity' => 1, 'acquisitioncost' => 552268, 'wattage' => 960, 'firsthour' => 315, 'succeeding' => 8],
            ['name' => 'Centifuge', 'description' => ' Hermle', 'quantity' => 1, 'acquisitioncost' => 140580, 'wattage' => 100, 'firsthour' => 83, 'succeeding' => 5],
            ['name' => 'electric microscope', 'description' => ' EUROMEX', 'quantity' => 1, 'acquisitioncost' => 20339.5, 'wattage' => 1, 'firsthour' => 16, 'succeeding' => 5],
            ['name' => 'electric microscope', 'description' => ' Olympus CX31RBSFA', 'quantity' => 1, 'acquisitioncost' => 131026.9, 'wattage' => 1, 'firsthour' => 77, 'succeeding' => 5],
            ['name' => 'electric microscope', 'description' => ' Olympus CX23', 'quantity' => 1, 'acquisitioncost' => 38392.86, 'wattage' => 1, 'firsthour' => 26, 'succeeding' => 5],
            ['name' => 'Fumehood', 'description' => ' Biobase', 'quantity' => 1, 'acquisitioncost' => 160000, 'wattage' => 1000, 'firsthour' => 101, 'succeeding' => 8],
            ['name' => 'Furnace', 'description' => ' Neytech', 'quantity' => 1, 'acquisitioncost' => 169950, 'wattage' => 2400, 'firsthour' => 118, 'succeeding' => 19],
            ['name' => 'incubator', 'description' => ' memmert', 'quantity' => 1, 'acquisitioncost' => 79950, 'wattage' => 800, 'firsthour' => 55, 'succeeding' => 6],
            ['name' => 'Inverted microscope', 'description' => ' Olympus', 'quantity' => 1, 'acquisitioncost' => 390178.57, 'wattage' => 30, 'firsthour' => 219, 'succeeding' => 5],
            ['name' => 'kymograph', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 348600, 'wattage' => 1, 'firsthour' => 196, 'succeeding' => 5],
            ['name' => 'Oven', 'description' => ' Binder, new', 'quantity' => 1, 'acquisitioncost' => 75000, 'wattage' => 2300, 'firsthour' => 65, 'succeeding' => 19],
            ['name' => 'Oven', 'description' => ' Binder, old', 'quantity' => 1, 'acquisitioncost' => 79200, 'wattage' => 2300, 'firsthour' => 67, 'succeeding' => 19],
            ['name' => 'Spectrophotometer', 'description' => ' Hanon', 'quantity' => 1, 'acquisitioncost' => 465000, 'wattage' => 100, 'firsthour' => 260, 'succeeding' => 5],
            ['name' => 'Spectrophotometer', 'description' => ' UNICO', 'quantity' => 1, 'acquisitioncost' => 230000, 'wattage' => 700, 'firsthour' => 137, 'succeeding' => 6],
            ['name' => 'toploading balance', 'description' => ' Sartorius', 'quantity' => 1, 'acquisitioncost' => 24500, 'wattage' => 0.75, 'firsthour' => 18, 'succeeding' => 5],
            ['name' => 'toploading balance', 'description' => ' symmetry', 'quantity' => 1, 'acquisitioncost' => 39618, 'wattage' => 9.6, 'firsthour' => 27, 'succeeding' => 5],
            ['name' => 'hotplate', 'description' => ' KIA', 'quantity' => 1, 'acquisitioncost' => 35000, 'wattage' => 1020, 'firsthour' => 32, 'succeeding' => 8],
            ['name' => 'hotplate', 'description' => ' Torrey Pines', 'quantity' => 1, 'acquisitioncost' => 27272.5, 'wattage' => 1200, 'firsthour' => 30, 'succeeding' => 10],
            ['name' => 'water bath', 'description' => ' Vision', 'quantity' => 1, 'acquisitioncost' => 52121.01, 'wattage' => 650, 'firsthour' => 39, 'succeeding' => 5],
            ['name' => 'Refrigerator', 'description' => ' GE', 'quantity' => 1, 'acquisitioncost' => 15000, 'wattage' => 286, 'firsthour' => 16, 'succeeding' => 5],
            ['name' => 'Refrigerator', 'description' => ' Haier', 'quantity' => 1, 'acquisitioncost' => 19800, 'wattage' => 95, 'firsthour' => 17, 'succeeding' => 5],
            ['name' => 'Rotary evaporator', 'description' => ' Buchi', 'quantity' => 1, 'acquisitioncost' => 357142.86, 'wattage' => 120, 'firsthour' => 202, 'succeeding' => 5],
            ['name' => 'Cooler w/o freezer', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 12000, 'wattage' => 91, 'firsthour' => 12, 'succeeding' => 5],
            ['name' => 'Ultrasonic cleaner', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 75000, 'wattage' => 25, 'firsthour' => 46, 'succeeding' => 5],
            ['name' => 'water analyzer', 'description' => ' horiba', 'quantity' => 1, 'acquisitioncost' => 222080, 'wattage' => 9.8, 'firsthour' => 127, 'succeeding' => 5],
            ['name' => 'stereo microscope', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 83386, 'wattage' => 1, 'firsthour' => 50, 'succeeding' => 5],
            ['name' => 'PH meter', 'description' => ' Eutech', 'quantity' => 1, 'acquisitioncost' => 24875, 'wattage' => 0, 'firsthour' => 22, 'succeeding' => 0],
            ['name' => 'PH meter', 'description' => ' pHtestr30 Oakton', 'quantity' => 1, 'acquisitioncost' => 7800, 'wattage' => 0, 'firsthour' => 18, 'succeeding' => 0],
            ['name' => 'Light meter', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 8250, 'wattage' => 0, 'firsthour' => 16, 'succeeding' => 0],
            ['name' => 'DO meter', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 45000, 'wattage' => 0, 'firsthour' => 39, 'succeeding' => 0],
            ['name' => 'Multi-parameter', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 150150, 'wattage' => 0, 'firsthour' => 94, 'succeeding' => 0],
            ['name' => 'Sugar refractometer', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 23000, 'wattage' => 0, 'firsthour' => 24, 'succeeding' => 0],
            ['name' => 'GPS', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 20000, 'wattage' => 0, 'firsthour' => 19, 'succeeding' => 0],
            ['name' => 'refractometer', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 8250, 'wattage' => 0, 'firsthour' => 10, 'succeeding' => 0],
            ['name' => 'non electric microscope', 'description' => '', 'quantity' => 1, 'acquisitioncost' => 3900, 'wattage' => 0, 'firsthour' => 8, 'succeeding' => 0],
        ];
        //Model::insert($data); // Eloquent
        //DB::table('items')->insert($data); // Query Builder
        foreach ($data as $item) {
            App\Item::insert($item);
        }
    }
}
