<?php

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [ 'name' =>  'Abney Hand Level', 'description' => 'Oaklet' ],
            [ 'name' =>  'Adapter', 'description' => 'Kimax, USA, 30 mm x 200 mm' ],
            [ 'name' =>  'Adapter', 'description' => 'Brandless, 30 mm x 195 mm' ],
            [ 'name' =>  '', 'description' => 'Brandless, 30 mm x 185 mm' ],
            [ 'name' =>  '', 'description' => 'Brandless, 21 mm x 165 mm' ],
            [ 'name' =>  'Air Con', 'description' => 'Carrier, Concepcion Industries' ],
            [ 'name' =>  'Alcohol Lamp', 'description' => '' ],
            [ 'name' =>  'Alcohol Lamp', 'description' => '' ],
            [ 'name' =>  'Ammeter', 'description' => 'Kyoritsu, Model KEW-EDM,' ],
            [ 'name' =>  'Ammeter', 'description' => 'Range 1A/5A DC' ],
            [ 'name' =>  '', 'description' => 'No. 83024643' ],
            [ 'name' =>  '', 'description' => 'No. 82052210' ],
            [ 'name' =>  '', 'description' => 'No. 83024651' ],
            [ 'name' =>  '', 'description' => 'No. 83024644' ],
            [ 'name' =>  '', 'description' => 'No. 83024642' ],
            [ 'name' =>  '', 'description' => 'Kyoritsu, Model SR-3P, Range 5A AC,' ],
            [ 'name' =>  '', 'description' => 'SN: 7711' ],
            [ 'name' =>  '', 'description' => 'Kyoritsu, Model SR-4P, 1 Ampere AC,' ],
            [ 'name' =>  '', 'description' => 'SN: 7711' ],
            [ 'name' =>  '', 'description' => 'Kyoritsu, Model MR-4P, Range 5A DC,' ],
            [ 'name' =>  '', 'description' => 'SN: 7710' ],
            [ 'name' =>  '', 'description' => 'Multi-Range, Model 301, 0-500 ma DC' ],
            [ 'name' =>  '', 'description' => '-Sangamo' ],
            [ 'name' =>  '', 'description' => '-Weston' ],
            [ 'name' =>  'Aquarium', 'description' => 'Glass, 23.5"x11.5"x14"' ],
            [ 'name' =>  'Aquarium Air Pump', 'description' => 'NS-B1' ],
            [ 'name' =>  'Aquarium Air Pump', 'description' => 'Besta B-II' ],
            [ 'name' =>  'Aspirator Bulb', 'description' => 'Rubber' ],
            [ 'name' =>  'Autoclave', 'description' => 'Vertical, electric, Precision, Scientific, 220 V, 2-gal cap., 14"x26", All American, US Mfr.,w/ support rack & removable container' ],
            [ 'name' =>  'Automatic Voltage Regulator', 'description' => 'Autovol, Nikko, N-500VA' ],
            [ 'name' =>  'Auto Numbering Machine', 'description' => 'Lion, Model C-71' ],
            [ 'name' =>  'Balance', 'description' => '' ],
            [ 'name' =>  'Balance', 'description' => 'Analytical' ],
            [ 'name' =>  '', 'description' => '-Electric, Sauter, Precision Balance Model' ],
            [ 'name' =>  '', 'description' => '424, 200-g cap., SN: 28757' ],
            [ 'name' =>  '', 'description' => '-Electric, Sauter, Type No. 424, 200-g' ],
            [ 'name' =>  '', 'description' => 'cap., SN: 24597' ],
            [ 'name' =>  '', 'description' => '-Manual, double pan' ],
            [ 'name' =>  '', 'description' => '-Double pan & set of weights, 200-g cap.,' ],
            [ 'name' =>  '', 'description' => 'TG-5288-28601' ],
            [ 'name' =>  '', 'description' => 'Dial-O-Gram, Model 1650, 2610-g cap.,' ],
            [ 'name' =>  '', 'description' => 'w/ 3-pc set of weights' ],
            [ 'name' =>  '', 'description' => 'Harvard Trip, Ohaus,double beam w/ 2-' ],
            [ 'name' =>  '', 'description' => 'stainless steel pans, 2-kg cap., SN: AD3958' ],
            [ 'name' =>  '', 'description' => 'Spring Scale' ],
            [ 'name' =>  '', 'description' => '-Globe, 0-1000 g cap.' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => '-Ohaus, 0-500 g cap.' ],
            [ 'name' =>  '', 'description' => 'Triple Beam, Ohaus, Model 2610, 2610-g' ],
            [ 'name' =>  '', 'description' => 'cap., w/ one pan & 3-pc set of weights' ],
            [ 'name' =>  '', 'description' => 'Triple Beam,Ohaus, 2610-g cap., SN: 86903' ],
            [ 'name' =>  'Barometer', 'description' => 'Aneroid, Demonstration, Takahashi Osaka,' ],
            [ 'name' =>  'Barometer', 'description' => 'SN: 5978' ],
            [ 'name' =>  'Basin', 'description' => 'Plastic' ],
            [ 'name' =>  'Basin', 'description' => '-Big' ],
            [ 'name' =>  '', 'description' => '-Small' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'Beaker', 'description' => '' ],
            [ 'name' =>  '-    50-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '-    50-ml', 'description' => 'Brandless' ],
            [ 'name' =>  '', 'description' => 'Schott' ],
            [ 'name' =>  '-  100-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '-  100-ml', 'description' => 'Brandless' ],
            [ 'name' =>  '', 'description' => 'Duran' ],
            [ 'name' =>  '-  150-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '-  150-ml', 'description' => '' ],
            [ 'name' =>  '-  250-ml', 'description' => 'Duran' ],
            [ 'name' =>  '-  250-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '', 'description' => 'Diamond' ],
            [ 'name' =>  '', 'description' => 'Kimax' ],
            [ 'name' =>  '-  400-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '-  400-ml', 'description' => 'Duran' ],
            [ 'name' =>  '-  600-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '-  600-ml', 'description' => '' ],
            [ 'name' =>  '-  800-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  '-1000-ml', 'description' => 'Pyrex, graduated, No. 1000' ],
            [ 'name' =>  'Bell', 'description' => 'Orchid callbell, black base' ],
            [ 'name' =>  'Bell', 'description' => 'Brandless, blue base' ],
            [ 'name' =>  'Blender', 'description' => 'Waring, Model 11B117, 1-L cap.' ],
            [ 'name' =>  'BOD Bottle', 'description' => 'Clear glass, w/ tapered glass stopper, 300-ml cap., Wheaton' ],
            [ 'name' =>  'BOD Bottle', 'description' => 'Nos. 43, 68 & 234' ],
            [ 'name' =>  '', 'description' => 'Nos. 4, 9, 29, 31, 31, 32, 32, 33, 34, 235, 238, 240' ],
            [ 'name' =>  'Borer', 'description' => '' ],
            [ 'name' =>  'Borer', 'description' => 'Cork, bronze, 6-pc set' ],
            [ 'name' =>  '', 'description' => 'Rubber, stainless, 6-pc set' ],
            [ 'name' =>  'Bulb', 'description' => 'G.E.' ],
            [ 'name' =>  'Bulb', 'description' => 'Philips, Holland' ],
            [ 'name' =>  '', 'description' => 'Toshiba, Japan' ],
            [ 'name' =>  'Bunsen Burner', 'description' => '' ],
            [ 'name' =>  'Bunsen Burner', 'description' => 'Tirill Type, US Mfr., PN 6200.1, w/' ],
            [ 'name' =>  '', 'description' => 'adjustment at base' ],
            [ 'name' =>  '', 'description' => 'W/ adjustment at side' ],
            [ 'name' =>  '', 'description' => 'Brandless' ],
            [ 'name' =>  'Burette', 'description' => '' ],
            [ 'name' =>  'Burette', 'description' => 'Acid, DIN, w/ glass stopcock, 50-ml cap., 0.1ml grad., 0.1ml tolerance, made in W. Germany' ],
            [ 'name' =>  '', 'description' => 'Base, ST, 50-ml cap., 0.1 ml grad., w/ pinch hook clamp, rubber tubing  & glass tip' ],
            [ 'name' =>  '', 'description' => '-Brandless' ],
            [ 'name' =>  'Burette Brush', 'description' => '36" long, w/ a large handle loop' ],
            [ 'name' =>  'Cabinet', 'description' => '' ],
            [ 'name' =>  'Cabinet', 'description' => 'Display, 6-shelves, 2-swing doors,' ],
            [ 'name' =>  '', 'description' => '59"x17"x32"' ],
            [ 'name' =>  '', 'description' => 'Filing, steel, gray, 4-drawers, 28"x19"x52"' ],
            [ 'name' =>  '', 'description' => 'Herbarium, green color, w/ 2-swing doors,' ],
            [ 'name' =>  '', 'description' => '37"x22"x58"' ],
            [ 'name' =>  '', 'description' => 'Herbarium, green color, steel, w/ 2-' ],
            [ 'name' =>  '', 'description' => 'swing doors, 53"x35"x24"' ],
            [ 'name' =>  '', 'description' => 'Index card, formica top, 11-small drawers' ],
            [ 'name' =>  '', 'description' => 'Mahogany, 2-swing doors, 36"x17"x32"' ],
            [ 'name' =>  '', 'description' => 'Nat. Sci. Exhibit Display, Narra, 2-sliding glass door' ],
            [ 'name' =>  '', 'description' => '-47"x24"x59", 3-shelves' ],
            [ 'name' =>  '', 'description' => '-60"x19"x59", 8-shelves, adjustable shelves' ],
            [ 'name' =>  '', 'description' => '-319"x24"x74", w/ (7) cases =three 3-shelves case & four 4-shelves case, each case w/ 2-sliding glass door' ],
            [ 'name' =>  'Calculator', 'description' => 'Scientific, Casio, 10-digit' ],
            [ 'name' =>  'Calculator', 'description' => '-fx-140' ],
            [ 'name' =>  '', 'description' => '-fx-100D, Super-FX' ],
            [ 'name' =>  'Caliper', 'description' => '' ],
            [ 'name' =>  'Caliper', 'description' => 'Micrometer, China, 0-25 mm, w/ box' ],
            [ 'name' =>  '', 'description' => 'Micrometer, 25x1 mm, w/ box' ],
            [ 'name' =>  '', 'description' => 'Vernier, General, stainless, 0-200 mm, 7407-22' ],
            [ 'name' =>  'Calorimeter', 'description' => 'Double wall, aluminum, 4 1/2" diameter' ],
            [ 'name' =>  'Camera', 'description' => 'Split-Image Finder, Asahi, Pentax, K1000' ],
            [ 'name' =>  'Centrifuge', 'description' => '' ],
            [ 'name' =>  'Centrifuge', 'description' => 'Electric, Safeguard, Clay Adams, 115 V' ],
            [ 'name' =>  '', 'description' => 'AC-DC, SN: 115222' ],
            [ 'name' =>  '', 'description' => 'Haematokrit, Hettich, SN: 2011' ],
            [ 'name' =>  '', 'description' => 'Manual' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'Chair', 'description' => '' ],
            [ 'name' =>  'Chair', 'description' => 'Ordinary, rattan seat' ],
            [ 'name' =>  '', 'description' => 'Ordinary, solid seat & back, mahogany' ],
            [ 'name' =>  '', 'description' => 'Ordinary, solid seat & back, nat. fin.' ],
            [ 'name' =>  '', 'description' => 'Swivel, maroon' ],
            [ 'name' =>  '', 'description' => 'Executive, upholstered, adjustable, BG-5200H' ],
            [ 'name' =>  '', 'description' => 'Wooden monobloc' ],
            [ 'name' =>  '', 'description' => '-Botany Lab1' ],
            [ 'name' =>  '', 'description' => '-Botany Lab2' ],
            [ 'name' =>  '', 'description' => '-Chemistry Lab' ],
            [ 'name' =>  '', 'description' => '-Physics Lab' ],
            [ 'name' =>  '', 'description' => '-Zoology Lab' ],
            [ 'name' =>  '', 'description' => '-DNSM Office' ],
            [ 'name' =>  '', 'description' => '-Lab. Office' ],
            [ 'name' =>  'Chart', 'description' => '' ],
            [ 'name' =>  'Chart', 'description' => 'Periodic Table of the Elements, wooden, @ Chem. Lab' ],
            [ 'name' =>  '', 'description' => 'Spectrum' ],
            [ 'name' =>  'Chromatographic Column', 'description' => 'Kimax, USA' ],
            [ 'name' =>  'Chromatographic Column', 'description' => '-530 mm x 30 mm' ],
            [ 'name' =>  '', 'description' => '-530 mm x 25 mm' ],
            [ 'name' =>  '', 'description' => '-330 mm x 30 mm' ],
            [ 'name' =>  '', 'description' => '-330 mm x 25 mm' ],
            [ 'name' =>  'Clamp', 'description' => '' ],
            [ 'name' =>  'Clamp', 'description' => 'Buret, double, plastic-coated jaws, green' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => 'Buret, double, w/ NSTA sticker' ],
            [ 'name' =>  '', 'description' => 'Buret, double' ],
            [ 'name' =>  '', 'description' => 'Buret, single, w/ one V-jaw & one flat jaw,' ],
            [ 'name' =>  '', 'description' => 'plastic covered jaws' ],
            [ 'name' =>  '', 'description' => 'Buret, single,  w/ round jaws' ],
            [ 'name' =>  '', 'description' => 'Buret, single, w/ round jaws, Castaloy,' ],
            [ 'name' =>  '', 'description' => 'Fisher' ],
            [ 'name' =>  '', 'description' => 'Holder, fixed, for rods up to 11/16 diam., jaw center to center' ],
            [ 'name' =>  '', 'description' => 'Pinch, for tubing, made of wire w/ rounded' ],
            [ 'name' =>  '', 'description' => 'edges, w/ finger grips' ],
            [ 'name' =>  '', 'description' => 'Universal, extension, plastic- coated jaw,' ],
            [ 'name' =>  '', 'description' => 'blue' ],
            [ 'name' =>  'Clinostat', 'description' => 'Electric, Griffin & George Ltd, 230 V' ],
            [ 'name' =>  'Cloud Chamber', 'description' => 'Hand operated, Shimadzu, Wilson,' ],
            [ 'name' =>  'Cloud Chamber', 'description' => 'SN: 534676' ],
            [ 'name' =>  'Colorimeter', 'description' => 'Spectronic 20, Bausch & Lomb, w/ 1/2" test tubes, Cat. No. 33-17-80, accessory for spectrophotometer' ],
            [ 'name' =>  'Compass', 'description' => '' ],
            [ 'name' =>  'Compass', 'description' => 'Staffhead, Tamaya, 4" diam., w/ case  &' ],
            [ 'name' =>  '', 'description' => 'accessory' ],
            [ 'name' =>  '', 'description' => 'Pocket size, Osaka Tamaya, w/ case' ],
            [ 'name' =>  '', 'description' => 'Small Size, 2 cm in diameter' ],
            [ 'name' =>  'Concave Microslides', 'description' => 'Gold Seal, Clay Adams, No. 3010' ],
            [ 'name' =>  'Concave Microslides', 'description' => '-Single Concavity' ],
            [ 'name' =>  '', 'description' => '-Double Concavity' ],
            [ 'name' =>  'Condenser', 'description' => 'General purpose for distillation & extraction' ],
            [ 'name' =>  'Condenser', 'description' => '-575 mm x 25 mm' ],
            [ 'name' =>  '', 'description' => '-530 mm x 30 mm' ],
            [ 'name' =>  '', 'description' => '-450 mm x 20 mm' ],
            [ 'name' =>  'Converter', 'description' => 'Power supply, solid state, Spartan,' ],
            [ 'name' =>  'Converter', 'description' => 'Model 691224-3A' ],
            [ 'name' =>  'Cork Board', 'description' => '1 m x 1 m' ],
            [ 'name' =>  'Counting Chamber', 'description' => '' ],
            [ 'name' =>  'Counting Chamber', 'description' => 'Hausser Scientific Partnership,' ],
            [ 'name' =>  '', 'description' => 'Cat. No. 800' ],
            [ 'name' =>  '', 'description' => 'Sedgewick Rafter, AO, set of 2 micrometer disc/box' ],
            [ 'name' =>  'Crucible', 'description' => 'Big, w/ cover, porcelain' ],
            [ 'name' =>  'Crucible', 'description' => '' ],
            [ 'name' =>  'Cutter', 'description' => 'Lion City, paper cutter w/ board' ],
            [ 'name' =>  'Desk', 'description' => '' ],
            [ 'name' =>  'Desk', 'description' => 'Junior., Executive, 3-side drawers, 1-center drawer, w/ glass top, 53 1/2"x28"x30"' ],
            [ 'name' =>  '', 'description' => 'Secretarial, 2-drawers, formica top,' ],
            [ 'name' =>  '', 'description' => '42"x25"x30"' ],
            [ 'name' =>  '', 'description' => 'L-shape, nat. fin., 1-center drawer, 2-side drawers, 54"x46"x29"' ],
            [ 'name' =>  '', 'description' => 'Mahogany, 1-center drawer, 36"x24"x30"' ],
            [ 'name' =>  'Dessicator', 'description' => '240 mm w/ porcelain plate' ],
            [ 'name' =>  'Dissecting Pan', 'description' => 'Aluminum, rectangular, 11"x7"' ],
            [ 'name' =>  'Dissecting Pan', 'description' => '-w/ wax' ],
            [ 'name' =>  '', 'description' => '-w/o wax' ],
            [ 'name' =>  'Dissecting Set', 'description' => '' ],
            [ 'name' =>  'Dissecting Set', 'description' => 'For cat, blue case' ],
            [ 'name' =>  '', 'description' => 'For frog, black case' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'D. O. Meter', 'description' => 'YSI, Model No. 57, SN: 8356' ],
            [ 'name' =>  'Drainer', 'description' => '' ],
            [ 'name' =>  'Drainer', 'description' => 'General, 16 1/2"x16 1/2"x13", gray' ],
            [ 'name' =>  '', 'description' => 'Test tube, 30"x18", gray' ],
            [ 'name' =>  'Drawing Attachment', 'description' => 'For AO Microstar Microscopes, Cat.' ],
            [ 'name' =>  'Drawing Attachment', 'description' => 'No. 1030' ],
            [ 'name' =>  'Dynamic Cart', 'description' => 'Principle of Momentum, 3-wheeled,' ],
            [ 'name' =>  'Dynamic Cart', 'description' => 'wooden, 10" long' ],
            [ 'name' =>  'Electric Hot Plate', 'description' => '' ],
            [ 'name' =>  'Electric Hot Plate', 'description' => 'Corning, Model PC-35' ],
            [ 'name' =>  '', 'description' => 'Thermolyne, Type 2200' ],
            [ 'name' =>  '', 'description' => '3D, Model EGO-2000, one-burner,' ],
            [ 'name' =>  '', 'description' => 'SN: 19811A' ],
            [ 'name' =>  'Electric Stove', 'description' => 'Northern Hill, Model NH 1500,' ],
            [ 'name' =>  'Electric Stove', 'description' => 'SN: KAM 9800' ],
            [ 'name' =>  'Electroscope', 'description' => 'Metal case' ],
            [ 'name' =>  'Evaporating Dish', 'description' => 'w/ pour-out' ],
            [ 'name' =>  'Flask', 'description' => '' ],
            [ 'name' =>  'Distilling', 'description' => 'Round bottom w/ side arm' ],
            [ 'name' =>  '-250-ml', 'description' => 'Pyrex, No. 4620' ],
            [ 'name' =>  '-500-ml', 'description' => 'Brandless' ],
            [ 'name' =>  'Erlenmeyer', 'description' => '' ],
            [ 'name' =>  '-   50-ml', 'description' => 'Kimax, No. 26500' ],
            [ 'name' =>  '-   50-ml', 'description' => 'Pyrex, No. 4980' ],
            [ 'name' =>  '', 'description' => 'Schott G20' ],
            [ 'name' =>  '-  125-ml', 'description' => 'Kimax, No. 26500' ],
            [ 'name' =>  '-  125-ml', 'description' => 'Pyrex, No. 4990' ],
            [ 'name' =>  '-  250-ml', 'description' => 'Duran' ],
            [ 'name' =>  '-  250-ml', 'description' => 'Kimax, No. 26500' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 4980' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => 'Schott' ],
            [ 'name' =>  '-  300-ml', 'description' => 'Kimax, No. 26500' ],
            [ 'name' =>  '-  500-ml', 'description' => 'Duran' ],
            [ 'name' =>  '-  500-ml', 'description' => 'Pyrex, No. 4980' ],
            [ 'name' =>  '-1000-ml', 'description' => 'Hario' ],
            [ 'name' =>  '-1000-ml', 'description' => 'Pyrex, No. 4980' ],
            [ 'name' =>  'Filtering', 'description' => '' ],
            [ 'name' =>  '-  500-ml', 'description' => 'Pyrex, No. 4980, w/ side tube' ],
            [ 'name' =>  'Florence', 'description' => '' ],
            [ 'name' =>  '-  250-ml', 'description' => 'Kimax, 24/40' ],
            [ 'name' =>  'Volumetric', 'description' => '' ],
            [ 'name' =>  '-   50-ml', 'description' => 'DIN E-MIL' ],
            [ 'name' =>  '- 100-ml', 'description' => 'Brandless' ],
            [ 'name' =>  '- 100-ml', 'description' => 'DIN' ],
            [ 'name' =>  '', 'description' => 'Duran' ],
            [ 'name' =>  '', 'description' => 'Normechliff' ],
            [ 'name' =>  '- 250-ml', 'description' => 'Pyrex, No. 5580' ],
            [ 'name' =>  '- 250-ml', 'description' => 'Pyrex, No. 5640' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 5642' ],
            [ 'name' =>  '', 'description' => 'SY' ],
            [ 'name' =>  '- 500-ml', 'description' => 'Pyrex, No. 5642' ],
            [ 'name' =>  '- 500-ml', 'description' => 'Pyrex, No. 5643' ],
            [ 'name' =>  'Foot Candle Meter', 'description' => 'Illuminometer, Kyoritsu, Model 5200,' ],
            [ 'name' =>  'Foot Candle Meter', 'description' => 'SN: 820816' ],
            [ 'name' =>  'Funnel', 'description' => '' ],
            [ 'name' =>  '-Buchner', 'description' => 'Porcelain, BN2' ],
            [ 'name' =>  '-Glass', 'description' => 'Brandless' ],
            [ 'name' =>  '-Glass', 'description' => 'Pyrex' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => 'Tenshiang' ],
            [ 'name' =>  '-Plastic', 'description' => '' ],
            [ 'name' =>  '-Separatory', 'description' => '' ],
            [ 'name' =>  '- 250-ml', 'description' => 'Brandless' ],
            [ 'name' =>  '- 250-ml', 'description' => 'Kimax' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => 'YC' ],
            [ 'name' =>  '- 500-ml', 'description' => 'Duran' ],
            [ 'name' =>  '- 500-ml', 'description' => 'Pyrex, No. 6402' ],
            [ 'name' =>  'Funnel Tube', 'description' => 'Thistle top, brandless' ],
            [ 'name' =>  'Funnel Tube', 'description' => 'W/ wide flared top, stem length 300 mm' ],
            [ 'name' =>  '', 'description' => 'W/ cylindrical top' ],
            [ 'name' =>  '', 'description' => '-stem length 300 mm' ],
            [ 'name' =>  '', 'description' => '-stem length 400 mm' ],
            [ 'name' =>  'Galvanometer', 'description' => 'Kyoritsu, Model EDM, Range 50 uA DC' ],
            [ 'name' =>  'Galvanometer', 'description' => 'SN: 052193' ],
            [ 'name' =>  '', 'description' => 'SN: 052194' ],
            [ 'name' =>  'Generator', 'description' => 'Magnetic, electric' ],
            [ 'name' =>  'Glass Beads', 'description' => '6 mm, solid' ],
            [ 'name' =>  'Graduated Cylinder', 'description' => '' ],
            [ 'name' =>  '-  10-ml', 'description' => 'EM Techcolor' ],
            [ 'name' =>  '-  10-ml', 'description' => 'Pyrex, No. 3025' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 3075' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '-  25-ml', 'description' => 'Pyrex, No. 3025' ],
            [ 'name' =>  '-  25-ml', 'description' => 'Pyrex, No. 3075' ],
            [ 'name' =>  '-100-ml', 'description' => 'Pyrex, No. 3075' ],
            [ 'name' =>  '-100-ml', 'description' => '' ],
            [ 'name' =>  '', 'description' => 'E20°C' ],
            [ 'name' =>  '-250-ml', 'description' => 'Duran' ],
            [ 'name' =>  '-250-ml', 'description' => 'E20°C' ],
            [ 'name' =>  '', 'description' => 'Ex20°Cml' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 3025' ],
            [ 'name' =>  '-500-ml', 'description' => 'Pyrex, No. 3025' ],
            [ 'name' =>  '-500-ml', 'description' => 'E20°C' ],
            [ 'name' =>  'Gyroscope', 'description' => '' ],
            [ 'name' =>  'Gyroscope', 'description' => 'Bicycle wheel' ],
            [ 'name' =>  '', 'description' => 'Simple form, Welch' ],
            [ 'name' =>  '', 'description' => 'Simple form, Welch' ],
            [ 'name' =>  'Hand Tally Counter', 'description' => '' ],
            [ 'name' =>  'Hand Tally Counter', 'description' => 'Plus' ],
            [ 'name' =>  '', 'description' => "Green Show's, Taiwan" ],
            [ 'name' =>  'Hemacytometer', 'description' => 'AO Spencer, Counter Skudom Thoma' ],
            [ 'name' =>  'Hemacytometer', 'description' => 'Cell' ],
            [ 'name' =>  "Hooke's Law Outfit Apparatus", 'description' => '' ],
            [ 'name' =>  "Hooke's Law Outfit Apparatus", 'description' => '' ],
            [ 'name' =>  'Hydrometer', 'description' => '' ],
            [ 'name' =>  'Hydrometer', 'description' => 'Double Scale, .700-1.000 & 70 to 10' ],
            [ 'name' =>  '', 'description' => 'Light Liquid, double scale, .700-1.000 & 70 to 10' ],
            [ 'name' =>  '', 'description' => 'Sult Cmce saccharomieer, 0-40' ],
            [ 'name' =>  'Hydrometer Set', 'description' => 'Hydrometer Baumes & Specific Gravity' ],
            [ 'name' =>  'Hydrometer Set', 'description' => 'Scale 1.000-2.000, Temp 15°C, 8-pc set' ],
            [ 'name' =>  'Incubator', 'description' => 'Electric, Heraeus, Model 5028,' ],
            [ 'name' =>  'Incubator', 'description' => 'SN: 8001299' ],
            [ 'name' =>  'Inoculating Chamber', 'description' => 'Wooden, w/ glass top, 35.5"x23.5"x23.5"' ],
            [ 'name' =>  'Inoculating Loop', 'description' => 'Aluminum' ],
            [ 'name' =>  'Inoculating Loop', 'description' => 'Glass' ],
            [ 'name' =>  'Inoculating Needle', 'description' => 'Aluminum' ],
            [ 'name' =>  'Inoculating Needle', 'description' => 'Glass' ],
            [ 'name' =>  'Insect Box', 'description' => 'W/ glass' ],
            [ 'name' =>  'Insect Box', 'description' => '-20"x12"x3"' ],
            [ 'name' =>  '', 'description' => '-16"X12"X3"' ],
            [ 'name' =>  'Insect Net', 'description' => 'Aluminum, frame diameter 10", handle length 36"' ],
            [ 'name' =>  'Iron Ring', 'description' => '4" diam., w/ side arm & clamp' ],
            [ 'name' =>  'Iron Stand', 'description' => '' ],
            [ 'name' =>  'Iron Stand', 'description' => 'Rectangular base, 25" high' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => 'I-shaped base, 36" high' ],
            [ 'name' =>  '', 'description' => 'Triangular base, 37.5" high' ],
            [ 'name' =>  'Jar', 'description' => '' ],
            [ 'name' =>  'Jar', 'description' => 'Bell, glass, for transpiration' ],
            [ 'name' =>  '', 'description' => '-Big, w/ knob' ],
            [ 'name' =>  '', 'description' => '-Small, w/ tubulated top opening' ],
            [ 'name' =>  '', 'description' => 'Killing, glass, 11.5" diameter' ],
            [ 'name' =>  'Kymograph', 'description' => 'W/ accessories' ],
            [ 'name' =>  'Laboratory Sink', 'description' => 'Concrete-made, built-in @ lab office,' ],
            [ 'name' =>  'Laboratory Sink', 'description' => '57.5"x36"x34"' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'Lens', 'description' => '' ],
            [ 'name' =>  'Lens', 'description' => 'Achromatic, 20x, Marx, Japan' ],
            [ 'name' =>  '', 'description' => 'Biconcave, 50 mm diameter' ],
            [ 'name' =>  '', 'description' => 'Biconvex, 50 mm diameter' ],
            [ 'name' =>  '', 'description' => 'Double Concave, 24 mm diameter' ],
            [ 'name' =>  '', 'description' => 'Double Convex, 87 mm diameter' ],
            [ 'name' =>  '', 'description' => 'Optical Concave, 2.5" diameter, 6-pc/case' ],
            [ 'name' =>  '', 'description' => 'Stereoscope, pocket size w/ case' ],
            [ 'name' =>  'Level', 'description' => 'Dumpy, Osaka Tamaya, w/ case,' ],
            [ 'name' =>  'Level', 'description' => 'SN: 770031' ],
            [ 'name' =>  'Life Vest', 'description' => 'Adult, orange' ],
            [ 'name' =>  'Magnet', 'description' => '' ],
            [ 'name' =>  'Magnet', 'description' => 'Bar, Japan, No. 1508-4, 6.5" long' ],
            [ 'name' =>  '', 'description' => 'Horse-shoe, General, England' ],
            [ 'name' =>  'Medicine Dropper', 'description' => 'Glass' ],
            [ 'name' =>  'Medicine Dropper', 'description' => 'Plastic' ],
            [ 'name' =>  'Meter Stick', 'description' => 'Made of hardwood, w/ a light permanently engraved scale, easy to read black line, both edges of one face is graduated' ],
            [ 'name' =>  'Micro-Capillary Reader', 'description' => 'Damon/IEC Division, circular type, Cat.' ],
            [ 'name' =>  'Micro-Capillary Reader', 'description' => 'No. 2201, SN: 22014253' ],
            [ 'name' =>  'Micrometer Disc', 'description' => 'Bausch & Lomb, No. 31-16-05, w/ case, Scale 5 mm' ],
            [ 'name' =>  'Micrometer Eyepiece', 'description' => '10x' ],
            [ 'name' =>  'Micrometer Stage', 'description' => '' ],
            [ 'name' =>  'Micrometer Stage', 'description' => 'AO, 2 mm div. into units of 0.01 mm,' ],
            [ 'name' =>  '', 'description' => 'w/ box' ],
            [ 'name' =>  '', 'description' => 'Reichert, Cat. 1400' ],
            [ 'name' =>  'Microprojector', 'description' => 'Ken-A-Vision, Model X1000-1,SN:9933' ],
            [ 'name' =>  'Microscope(See Annex A for details)', 'description' => '' ],
            [ 'name' =>  'Microtome', 'description' => '' ],
            [ 'name' =>  'Microtome', 'description' => 'Custom, Rotary, manual, Damon/IEC Division, SN: 3310145' ],
            [ 'name' =>  '', 'description' => 'SMIC, Germany' ],
            [ 'name' =>  'Microtome Knife', 'description' => '' ],
            [ 'name' =>  'Microtome Knife', 'description' => '120 mm long, Box No. 387' ],
            [ 'name' =>  '', 'description' => 'Reichert-Jung, Damon/IEC Division, 120' ],
            [ 'name' =>  '', 'description' => 'mm long, Cat. No. 3257' ],
            [ 'name' =>  'Mirror', 'description' => 'China, 50 mm diameter, 25 cm focus' ],
            [ 'name' =>  'Mirror', 'description' => '-Concave' ],
            [ 'name' =>  '', 'description' => '-Convex' ],
            [ 'name' =>  'Model', 'description' => '' ],
            [ 'name' =>  'Model', 'description' => 'Animal Brain, B-174-7' ],
            [ 'name' =>  '', 'description' => 'Atomic, molecular, orbital' ],
            [ 'name' =>  '', 'description' => 'Brain, local' ],
            [ 'name' =>  '', 'description' => 'Dicot stem, dissected, S-605' ],
            [ 'name' =>  '', 'description' => 'Fish, dissected' ],
            [ 'name' =>  '', 'description' => 'Flower, dissected' ],
            [ 'name' =>  '', 'description' => 'Human Embryology, B-166 w/ the ff:' ],
            [ 'name' =>  '', 'description' => '-female pelvis' ],
            [ 'name' =>  '', 'description' => '-one-month embryo' ],
            [ 'name' =>  '', 'description' => '-three-month embryo' ],
            [ 'name' =>  '', 'description' => '-five-month embryo lying on the back' ],
            [ 'name' =>  '', 'description' => 'Monocot stem, dissected, S-605' ],
            [ 'name' =>  '', 'description' => 'Organic Chemistry Model Kit, 12-set/box' ],
            [ 'name' =>  '', 'description' => '-Hydrocarbons, Cat. No. 131' ],
            [ 'name' =>  '', 'description' => '-Functional Groups, Cat. No. 132' ],
            [ 'name' =>  '', 'description' => '-Isomers, Cat. No. 133' ],
            [ 'name' =>  '', 'description' => 'Plant Mitosis' ],
            [ 'name' =>  '', 'description' => 'Scalp & skin, dissected, B-156' ],
            [ 'name' =>  '', 'description' => 'Typical angiosperm leaf' ],
            [ 'name' =>  'Moment of Inertia Apparatus', 'description' => 'Round aluminum (4.5" diameter) & wood (24"x5")' ],
            [ 'name' =>  'Mortar and Pestle', 'description' => 'Porcelain, w/ pouring lip' ],
            [ 'name' =>  'Multitester', 'description' => 'Sanwa, YX-360TRs' ],
            [ 'name' =>  'Omniclave', 'description' => 'Model OCM, A3-44950' ],
            [ 'name' =>  'Oscilloscope', 'description' => 'RCA, WO-88A, SN: 9592' ],
            [ 'name' =>  'Oven', 'description' => '' ],
            [ 'name' =>  'Oven', 'description' => 'Drying, Memmert, Model-TV, 220V, SN: 790-407' ],
            [ 'name' =>  '', 'description' => 'Drying, wooden, locally fabricated, 51"x20 1/2"x40"' ],
            [ 'name' =>  '', 'description' => 'Electric, Heraeus, Model T-5042, SN: 8008055' ],
            [ 'name' =>  'Pail', 'description' => 'Plastic, light green' ],
            [ 'name' =>  'Pencil Sharpener', 'description' => 'Prince, PS-1' ],
            [ 'name' =>  'Pendulum', 'description' => 'Ballistic' ],
            [ 'name' =>  'Pendulum', 'description' => '' ],
            [ 'name' =>  'Pendulum Bob', 'description' => 'Metal, local, ball bearing, 4-pc set' ],
            [ 'name' =>  'Petri Dish', 'description' => '' ],
            [ 'name' =>  'Petri Dish', 'description' => 'Kimax' ],
            [ 'name' =>  '', 'description' => 'Petriq' ],
            [ 'name' =>  '', 'description' => 'Pyrex' ],
            [ 'name' =>  '', 'description' => 'Pyrex' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'pH Meter', 'description' => '' ],
            [ 'name' =>  'pH Meter', 'description' => 'Corning, Model 7, 220V, w/ accessories: Electrode Lead/pH, Ion Selective Electrode (Corning, pH triple purpose, Cat. No. 00311101J, SN: 07452' ],
            [ 'name' =>  '', 'description' => 'Orion, Model 420A, SN: 2966' ],
            [ 'name' =>  '', 'description' => 'Philips, Pye Unicam, Type PW 9418/31, SN: 285796, w/ accessories:' ],
            [ 'name' =>  '', 'description' => '-Pye Unicam, Ingold, Cat. No. 401E7, SN: 548457' ],
            [ 'name' =>  '', 'description' => '-Corning, Great Britain, Cat. No. 00311602H, SN: 005065' ],
            [ 'name' =>  '', 'description' => '-Corning, Great Britain, pH triple purpose, Cat. No. 00311101J, SN: 011466' ],
            [ 'name' =>  'Pipet', 'description' => '' ],
            [ 'name' =>  '-Delivery', 'description' => '' ],
            [ 'name' =>  '-  1-ml', 'description' => 'Pyrex, No. 7102' ],
            [ 'name' =>  '-  2-ml', 'description' => 'Pyrex, No. 7102' ],
            [ 'name' =>  '-  5-ml', 'description' => 'E-Mil BS 1583' ],
            [ 'name' =>  '-10-ml', 'description' => 'Pyrex, No. 7102' ],
            [ 'name' =>  '-Measuring', 'description' => '' ],
            [ 'name' =>  '-  1-ml', 'description' => 'Pyrex, No. 7085' ],
            [ 'name' =>  '-  2-ml', 'description' => 'ExB' ],
            [ 'name' =>  '-  2-ml', 'description' => 'Pyrex, No. 7085' ],
            [ 'name' =>  '-  5-ml', 'description' => 'Pyrex, No. 7065' ],
            [ 'name' =>  '-10-ml', 'description' => 'DIN' ],
            [ 'name' =>  '-10-ml', 'description' => 'Pyrex, No. 7065' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 7085' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 7065' ],
            [ 'name' =>  '', 'description' => 'Pyrex, No. 7085' ],
            [ 'name' =>  'Pipet Rack', 'description' => 'For 1-ml measuring pipet, 12-hole' ],
            [ 'name' =>  'Pith Ball', 'description' => 'Aluminum coated, 6-pc/set' ],
            [ 'name' =>  'Plant Presser', 'description' => 'Wooden' ],
            [ 'name' =>  'Plier', 'description' => '' ],
            [ 'name' =>  'Plier', 'description' => 'Flat nose, insulated handle, orange color,' ],
            [ 'name' =>  '', 'description' => '7" long' ],
            [ 'name' =>  '', 'description' => 'Long nose, insulated handle, orange color, 6" long' ],
            [ 'name' =>  'Plumb Bob', 'description' => 'Blue color' ],
            [ 'name' =>  'Potentiometer', 'description' => 'Omnilab Scientific' ],
            [ 'name' =>  'Prepared Slides(See Annex B for details)', 'description' => '' ],
            [ 'name' =>  '1. UPOU - (1) box w/ (25) UPOU slides', 'description' => '' ],
            [ 'name' =>  '1. UPOU - (1) box w/ (25) UPOU slides', 'description' => 'Box #321 - 25 slides' ],
            [ 'name' =>  '2. Botany - (5) boxes w/ (267) slides', 'description' => '' ],
            [ 'name' =>  '2. Botany - (5) boxes w/ (267) slides', 'description' => 'Box #305 - 44 slides' ],
            [ 'name' =>  '', 'description' => 'Box #306 - 77 slides' ],
            [ 'name' =>  '', 'description' => 'Box #307 - 45 slides' ],
            [ 'name' =>  '', 'description' => 'Box #308 - 36 slides' ],
            [ 'name' =>  '', 'description' => 'Box #309 - 65 slides' ],
            [ 'name' =>  '2. Embryology - (5) boxes w/ (294) slides', 'description' => '' ],
            [ 'name' =>  '2. Embryology - (5) boxes w/ (294) slides', 'description' => 'Box #3     - 80 slides' ],
            [ 'name' =>  '', 'description' => 'Box #4     - 35 slides' ],
            [ 'name' =>  '', 'description' => 'Box #9     - 74 slides' ],
            [ 'name' =>  '', 'description' => 'Box #317 - 79 slides' ],
            [ 'name' =>  '', 'description' => 'Box #319 - 26 slides' ],
            [ 'name' =>  '3. Histology - (4) boxes w/ (223) slides', 'description' => '' ],
            [ 'name' =>  '3. Histology - (4) boxes w/ (223) slides', 'description' => 'Box #311 - 47 slides' ],
            [ 'name' =>  '', 'description' => 'Box #312 -100 slides' ],
            [ 'name' =>  '', 'description' => 'Box #313 - 40 slides' ],
            [ 'name' =>  '', 'description' => 'Box #326 - 36 slides' ],
            [ 'name' =>  '4. Zoology - (2) boxes w/ (114) slides', 'description' => '' ],
            [ 'name' =>  '4. Zoology - (2) boxes w/ (114) slides', 'description' => 'Box #310 - 42 slides' ],
            [ 'name' =>  '', 'description' => 'Box #325 - 72 slides' ],
            [ 'name' =>  '5. Parasitology - (2) boxes w/ (134) slides', 'description' => '' ],
            [ 'name' =>  '5. Parasitology - (2) boxes w/ (134) slides', 'description' => 'Box #1     -100 slides' ],
            [ 'name' =>  '', 'description' => 'Box #316 -  34 slides' ],
            [ 'name' =>  '6. Entomology - (7) boxes w/ (303) slides', 'description' => '' ],
            [ 'name' =>  '6. Entomology - (7) boxes w/ (303) slides', 'description' => 'Box #299 - 47 slides' ],
            [ 'name' =>  '', 'description' => 'Box #300 - 44 slides' ],
            [ 'name' =>  '', 'description' => 'Box #301 - 48 slides' ],
            [ 'name' =>  '', 'description' => 'Box #302 - 39 slides' ],
            [ 'name' =>  '', 'description' => 'Box #303 - 44 slides' ],
            [ 'name' =>  '', 'description' => 'Box #304 - 46 slides' ],
            [ 'name' =>  '', 'description' => 'Box #324 - 35 slides' ],
            [ 'name' =>  '7. Mixed Prepared Slides - (3) boxes w/ (154) slides', 'description' => '' ],
            [ 'name' =>  '7. Mixed Prepared Slides - (3) boxes w/ (154) slides', 'description' => 'Box #1    - 33 slides' ],
            [ 'name' =>  '', 'description' => 'Box #2    - 84 slides' ],
            [ 'name' =>  '', 'description' => 'Box #10  - 37 slides' ],
            [ 'name' =>  'Pressure Cooker', 'description' => 'All American, 41-quart cap., w/o support' ],
            [ 'name' =>  'Pressure Cooker', 'description' => 'rack' ],
            [ 'name' =>  'Pulley', 'description' => '' ],
            [ 'name' =>  'Pulley', 'description' => 'Ball bearing, aluminum, 35 KDD USA' ],
            [ 'name' =>  '', 'description' => 'Metal rod type' ],
            [ 'name' =>  '', 'description' => 'Metal table clamp' ],
            [ 'name' =>  '', 'description' => 'Metal tandem' ],
            [ 'name' =>  '', 'description' => 'Single' ],
            [ 'name' =>  '', 'description' => 'Triple tandem' ],
            [ 'name' =>  'Puncher', 'description' => 'Prince, 2-hole punch' ],
            [ 'name' =>  'Quadrat', 'description' => 'Steel, improvised, 1m x1m' ],
            [ 'name' =>  'Radiometer', 'description' => '' ],
            [ 'name' =>  'Reading Glass/Hand Lens', 'description' => 'Magnifying, 2" in diameter' ],
            [ 'name' =>  'Reading Glass/Hand Lens', 'description' => '' ],
            [ 'name' =>  'Reagent Bottle', 'description' => 'Narrow mouth, round, w/ glass flat-top stopper, 250-ml cap.' ],
            [ 'name' =>  'Refractometer', 'description' => '' ],
            [ 'name' =>  'Refractometer', 'description' => 'Hand, Atago, Japan, S/Mill, Salinity: 0~100%, No. 8808' ],
            [ 'name' =>  '', 'description' => 'Salinity, Japan, SN: 14099' ],
            [ 'name' =>  'Refrigerator', 'description' => '' ],
            [ 'name' =>  'Refrigerator', 'description' => 'G.E., 9 cu. ft., Make 139A 0772, SN: R-100DL, 220V' ],
            [ 'name' =>  '', 'description' => 'Kelvinator, 8 cu. ft.,no frost, 2-door' ],
            [ 'name' =>  'Resistance Box', 'description' => '' ],
            [ 'name' =>  'Rheostat', 'description' => '' ],
            [ 'name' =>  'Rheostat', 'description' => 'Cenco, 175 ohm, 1.5 A' ],
            [ 'name' =>  '', 'description' => 'Rotary, laboratory' ],
            [ 'name' =>  'Rubber Gong', 'description' => 'For tuning fork, 7.3" long' ],
            [ 'name' =>  'Salinometer', 'description' => 'Atago Tanaka, Japan, S-100' ],
            [ 'name' =>  'Scissors', 'description' => 'Metal, 6.8" long' ],
            [ 'name' =>  'Senior Volt Ohmyst', 'description' => 'RCA, Code 1156, Type WV-98A, SN: 24032' ],
            [ 'name' =>  'Set of Weights', 'description' => '' ],
            [ 'name' =>  'Set of Weights', 'description' => 'For Analytical Balance, Grade 3, China, SN: 363., 21-pc set = (1) 100-g, (1) 50-g, (2) 20-g, (1) 10-g, (1) 5-g, (2) 2-g, (1) 1-g, (1) 500-mg, (2) 200-mg, (1) 100-mg, (1) 50-mg, (2) 20-mg, (1) 10-mg, (1) 5-mg, (2) 2-mg, (1) 1-mg' ],
            [ 'name' =>  '', 'description' => 'For Dial-o-Gram Balance, 3-pc set = (2) 1-kg, (1) 500-g' ],
            [ 'name' =>  '', 'description' => 'For Ohaus Triple Beam Balance, 3-pc set = (2) 1000-g, (1) 500-g' ],
            [ 'name' =>  '', 'description' => 'Solid brass, 13-pc set = (1)1000-g, (1) 500-g, (1) 200-g, (2) 100-g, (1) 50-g, (1) 20-g, (2) 10-g, (1) 5-g, (2) 2-g, (1) 1-g' ],
            [ 'name' =>  'Shelf', 'description' => '' ],
            [ 'name' =>  'Shelf', 'description' => 'Lab, 6-open shelves, 36"x17"x32"' ],
            [ 'name' =>  '', 'description' => 'Lab, formica top, 4-small open shelves, 2-big open shelves, 63"x17"x32"' ],
            [ 'name' =>  '', 'description' => 'Built-in at lab., 12-open shelves, 4 shelves w/ 2-sliding glass door, 189"x17.2"x97.5"' ],
            [ 'name' =>  '', 'description' => 'Built-in at lab., 21-open shelves, 189"x17.2"x97.5"' ],
            [ 'name' =>  '', 'description' => 'Built-in at lab. stockroom, 20-open shelves, 238"x16.3"x52"' ],
            [ 'name' =>  '', 'description' => 'Built-in at lab. stockroom, 22-open shelves, 248.5"x13"x35.8"' ],
            [ 'name' =>  'Slide Warmer', 'description' => 'Everbach, 115V, 45W' ],
            [ 'name' =>  'Soldering Gun', 'description' => 'Weller, 8200D, 100/140W, 220/240V' ],
            [ 'name' =>  'Soxhlet', 'description' => '' ],
            [ 'name' =>  'Soxhlet', 'description' => 'Condenser, Kimax USA' ],
            [ 'name' =>  '', 'description' => '34/15' ],
            [ 'name' =>  '', 'description' => '45/50' ],
            [ 'name' =>  '', 'description' => 'Tube, Kimax USA' ],
            [ 'name' =>  '', 'description' => '34/45' ],
            [ 'name' =>  '', 'description' => '45/50' ],
            [ 'name' =>  'Spatula', 'description' => 'Stainless, steel' ],
            [ 'name' =>  'Spatula', 'description' => '-big' ],
            [ 'name' =>  '', 'description' => '-small' ],
            [ 'name' =>  'Spectrophotometer', 'description' => 'Spectronic 20, Bausch & Lomb,' ],
            [ 'name' =>  'Spectrophotometer', 'description' => 'SN: 0718080Y' ],
            [ 'name' =>  'Spin Bar', 'description' => 'Magnetic' ],
            [ 'name' =>  'Spot Plate', 'description' => '' ],
            [ 'name' =>  'Spot Plate', 'description' => 'Glass, 9-hole' ],
            [ 'name' =>  '', 'description' => 'Porcelain, 12-hole' ],
            [ 'name' =>  'Spring', 'description' => '' ],
            [ 'name' =>  'Stadia Rod', 'description' => 'Wooden, orange, 3 m' ],
            [ 'name' =>  'Stand', 'description' => 'For funnel, wooden, blue, 5-hole' ],
            [ 'name' =>  'Stapler', 'description' => 'No. 10' ],
            [ 'name' =>  'Sterilizer', 'description' => 'Electric, stainless steel' ],
            [ 'name' =>  'Stirring Rod', 'description' => 'Glass, 10" long' ],
            [ 'name' =>  'Stirring Rod', 'description' => '' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'Stirrir', 'description' => '' ],
            [ 'name' =>  'Stirrir', 'description' => 'Magnetic, Globe, Shanghai China, Model 791, Lot No. 9882' ],
            [ 'name' =>  '', 'description' => 'Magnetic, Corning, PC-353' ],
            [ 'name' =>  'Stopper', 'description' => 'Rubber' ],
            [ 'name' =>  'Stopwatch', 'description' => '' ],
            [ 'name' =>  'Stopwatch', 'description' => 'Brandless, white' ],
            [ 'name' =>  '', 'description' => 'Sports Yachting, Star Master, Swiss made' ],
            [ 'name' =>  'Syracuse Dish', 'description' => 'Clear glass, w/ a groove in the bottom & beveled for stacking' ],
            [ 'name' =>  'Tank', 'description' => 'LPG' ],
            [ 'name' =>  'Tape', 'description' => 'Measuring, fiber glass, 50m, KYK Tools' ],
            [ 'name' =>  'Telescope', 'description' => 'Shimadzu N53' ],
            [ 'name' =>  'Test Tube', 'description' => '10" length' ],
            [ 'name' =>  'Test Tube', 'description' => '8" length' ],
            [ 'name' =>  '', 'description' => '7" length' ],
            [ 'name' =>  '', 'description' => '6" length' ],
            [ 'name' =>  '', 'description' => '5" length' ],
            [ 'name' =>  '', 'description' => '4" length' ],
            [ 'name' =>  '', 'description' => 'Micro test tube, 3" length' ],
            [ 'name' =>  '', 'description' => 'Centrifuge tube, conical' ],
            [ 'name' =>  '', 'description' => '-Pyrex, graduated, 12-ml' ],
            [ 'name' =>  '', 'description' => '-Pyrex, No. 9800, 12-ml' ],
            [ 'name' =>  '', 'description' => '-Brandless, 12-ml' ],
            [ 'name' =>  '', 'description' => '-Brandless, 15-ml' ],
            [ 'name' =>  '', 'description' => '-Pyrex, No. 8080, grad., 15-ml' ],
            [ 'name' =>  '', 'description' => '-Duran, 10-ml' ],
            [ 'name' =>  'Test Tube Brush', 'description' => 'Straight tuft w/ separate tufted end &' ],
            [ 'name' =>  'Test Tube Brush', 'description' => 'large loop handle' ],
            [ 'name' =>  'Test Tube Holder', 'description' => 'Made of wire w/ curved quadrangular jaws, 5.5" long' ],
            [ 'name' =>  'Test Tube Rack', 'description' => 'Wooden' ],
            [ 'name' =>  'Test Tube Rack', 'description' => '-big, 18-hole' ],
            [ 'name' =>  '', 'description' => '-small, 30-hole, for micro test tubes' ],
            [ 'name' =>  'Thermometer', 'description' => '' ],
            [ 'name' =>  'Thermometer', 'description' => 'Clinical, Japan, 1M.C' ],
            [ 'name' =>  '', 'description' => 'Field' ],
            [ 'name' =>  '', 'description' => '100°C' ],
            [ 'name' =>  '', 'description' => '110°C' ],
            [ 'name' =>  '', 'description' => '240°C' ],
            [ 'name' =>  '', 'description' => '300°C' ],
            [ 'name' =>  '', 'description' => '360°C' ],
            [ 'name' =>  '', 'description' => 'Veterinary, Terumo Japan, Prismatic Type, JT-9, w/ clip & string, 10-pc box' ],
            [ 'name' =>  'Thermos Bottle', 'description' => '' ],
            [ 'name' =>  'Thermos Bottle', 'description' => 'Ching Kiang Brand, China' ],
            [ 'name' =>  '', 'description' => 'Sunflower, Shanghai China' ],
            [ 'name' =>  'Timer', 'description' => '' ],
            [ 'name' =>  'Timer', 'description' => 'Electric, Gralab, Model 173' ],
            [ 'name' =>  '', 'description' => 'Manual, General Electric, Model 776, Hong Kong' ],
            [ 'name' =>  'Tongs', 'description' => '' ],
            [ 'name' =>  'Tongs', 'description' => 'Crucible, small' ],
            [ 'name' =>  '', 'description' => 'Crucible, big' ],
            [ 'name' =>  '', 'description' => 'Laboratory' ],
            [ 'name' =>  'Transformer', 'description' => '' ],
            [ 'name' =>  'Transformer', 'description' => 'Demonstration, Triad, SN: 6035' ],
            [ 'name' =>  '', 'description' => 'Lamp, Vertan, Lucky Light, for one line volts 220 AC, 20W' ],
            [ 'name' =>  '', 'description' => 'Nippo, WAM Electronics, Model VT-500, Type: Auto, 500W' ],
            [ 'name' =>  '', 'description' => 'Shimadzu Seisakusho, Type DT-10, No. G-1134' ],
            [ 'name' =>  '', 'description' => 'Vertan, 500W' ],
            [ 'name' =>  '', 'description' => 'Wild Heerbrugg, Type MTR 28, Stock No. 363205' ],
            [ 'name' =>  '', 'description' => 'Yamato, MVS-5, 110-220V, 500W' ],
            [ 'name' =>  'Tray', 'description' => '' ],
            [ 'name' =>  'Tray', 'description' => 'Aluminum, 18"x14"' ],
            [ 'name' =>  '', 'description' => 'Enamel' ],
            [ 'name' =>  '', 'description' => '-17 1/2"x12"' ],
            [ 'name' =>  '', 'description' => '-13 1/2"x10"' ],
            [ 'name' =>  '', 'description' => 'Wooden, laboratory, w/ handle' ],
            [ 'name' =>  '', 'description' => '-15"x11"x7", blue' ],
            [ 'name' =>  '', 'description' => '-21 1/2"x12 1/2"x3", white, fabricated' ],
            [ 'name' =>  'Tripod', 'description' => '' ],
            [ 'name' =>  'Tripod', 'description' => 'Iron, for bunsen burner' ],
            [ 'name' =>  '', 'description' => 'Wooden' ],
            [ 'name' =>  '', 'description' => '-Brown, CE 232, for transit' ],
            [ 'name' =>  '', 'description' => '-Red, for wooden transit, yellow base' ],
            [ 'name' =>  '', 'description' => '-Red' ],
            [ 'name' =>  'Trough', 'description' => 'Galvanized iron, w/ rolled edge & overflow tube, 10"x7 1/2"' ],
            [ 'name' =>  'Tuning Fork', 'description' => '' ],
            [ 'name' =>  'Tuning Fork', 'description' => 'Electrically driven, Komet' ],
            [ 'name' =>  '', 'description' => 'West Germany' ],
            [ 'name' =>  '', 'description' => '-c² 512' ],
            [ 'name' =>  '', 'description' => '-g¹ 384' ],
            [ 'name' =>  'Typewriter', 'description' => 'Olympia, portable, 458104' ],
            [ 'name' =>  'Voltmeter', 'description' => '' ],
            [ 'name' =>  'Voltmeter', 'description' => 'Hangchow, J-DB4XA, 0-15V' ],
            [ 'name' =>  '', 'description' => 'Kyoritsu, Model C3-3P, 0-300V AC, SN: 7712' ],
            [ 'name' =>  'Wash Bottle', 'description' => 'Narrow mouth, cap & nozzle molded in one piece' ],
            [ 'name' =>  'Watch Glass', 'description' => '' ],
            [ 'name' =>  'Watch Glass', 'description' => 'Brandless, 2.4" to 4.8" diameter' ],
            [ 'name' =>  '', 'description' => 'Pyrex, big, 3.8" diameter' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'Water Bath', 'description' => '' ],
            [ 'name' =>  'Water Bath', 'description' => 'Aluminum, 6" diameter, 2.5" depth' ],
            [ 'name' =>  '', 'description' => 'Copper, hemispherical, shallow form, 6-ring, 6" diam., 2.5" dp.' ],
            [ 'name' =>  'Water Container', 'description' => 'Plastic' ],
            [ 'name' =>  'Water Container', 'description' => '-Blue, Orocan, 48L cap.' ],
            [ 'name' =>  '', 'description' => '-Green, 104L cap.' ],
            [ 'name' =>  '', 'description' => '-Pink, Orocan, 80L' ],
            [ 'name' =>  '', 'description' => '-Kennex Container, for distilled water, orange lid' ],
            [ 'name' =>  'Water Distilling Apparatus', 'description' => 'Monodest, Model 30000' ],
            [ 'name' =>  'Water Distilling Apparatus', 'description' => 'SN: 09MO84' ],
            [ 'name' =>  '', 'description' => 'SN: 09MO97' ],
            [ 'name' =>  'Wave Motion Apparatus', 'description' => '' ],
            [ 'name' =>  'Wheel and Axle', 'description' => 'Aluminum' ],
            [ 'name' =>  'Wire Gauze', 'description' => 'Squares, made of wire w/ turned edges' ],
            [ 'name' =>  'Wire', 'description' => 'Nichrome' ],
            [ 'name' =>  'Wire', 'description' => '' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  '', 'description' => '' ],
            [ 'name' =>  'Aspirator Bulb', 'description' => 'Rubber' ],
            [ 'name' =>  'Autoclave', 'description' => 'Clinical, Prestige, Extended Type, Medical Series 2100, Model No. 210002, SN: FJ21028, Made in England' ],
            [ 'name' =>  'Balance', 'description' => 'Precision, Basic Life, Sartorius, Model BL610, SN: 91203925' ],
            [ 'name' =>  'D.O. Meter', 'description' => 'YSI, Model 51B, SN: 95L43658' ],
            [ 'name' =>  'Milliammeter', 'description' => 'Camsco, Model 670, Range DC-50mA' ],
            [ 'name' =>  'Multitester', 'description' => 'Sunwa, YX-360TRD' ],
            [ 'name' =>  'Petri Dish', 'description' => 'Anumbra' ],
            [ 'name' =>  'Screw Driver', 'description' => 'Stanley, 6-pc set = 1 pt. Phillips, 2 pt.' ],
            [ 'name' =>  'Screw Driver', 'description' => 'Phillips, 3¯ cabinet, 4¯ standard,' ],
            [ 'name' =>  '', 'description' => '6¯ cabinet & 6¯ standard' ],
            [ 'name' =>  'Test Tube', 'description' => 'Brandless, 150"x16"' ],
            [ 'name' =>  'Voltmeter', 'description' => 'Camsco, Type YH670, Model 670, Range DC, 0-15 V' ],
            [ 'name' =>  'Wire Gauze', 'description' => 'Squares, made of wire w/ turned edges' ],

        ];

        //Model::insert($data); // Eloquent
        //DB::table('items')->insert($data); // Query Builder
        foreach($data as $item){
            App\Item::insert($item);
        }
    }
}
